using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EntVenta
{
    public class ExcelHelpers
    {
        public enum COLUMNAS_EXCEL
        {
            A = 1,
            B = 2,
            C = 3,
            D = 4,
            E = 5,
            F = 6,
            G = 7,
            H = 8,
            I = 9,
            J = 10,
            L = 11,
            M = 12,
            N = 13,
            O = 14,
            P = 15,
            Q = 16,
            R = 17,
            S = 18,
            T = 19,
            U = 20,
            V = 21,
            W = 22,
            X = 23,
            Y = 24,
            Z = 25,
            AA = 26,
            AB = 27,
            AC = 28,
            AD = 29,
            AE = 30,
            AF = 31,
            AG = 32,
            AH = 33,
            AI = 34,
            AJ = 35,
            AL = 36,
            AM = 37,
            AN = 38,
            AO = 39,
            AP = 40,
            AQ = 41,
            AR = 42,
            AS = 43,
            AT = 44,
            AU = 45,
            AV = 46,
            AW = 47,
            AX = 48,
            AY = 49,
            AZ = 50,
            BA = 51,
            BB = 52,
            BC = 53,
            BD = 54,
            BE = 55,
            BF = 56,
            BG = 57,
            BH = 58,
            BI = 59,
            BJ = 60,
            BL = 61,
            BM = 62,
            BN = 63,
            BO = 64,
            BP = 65,
            BQ = 66,
            BR = 67,
            BS = 68,
            BT = 69,
            BU = 70,
            BV = 71,
            BW = 72,
            BX = 73,
            BY = 74,
            BZ = 75,
            CA = 76,
            CB = 77,
            CC = 78,
            CD = 79,
            CE = 80,
            CF = 81,
            CG = 82,
            CH = 83,
            CI = 84,
            CJ = 85,
            CL = 86,
            CM = 87,
            CN = 88,
            CO = 89,
            CP = 90,
            CQ = 91,
            CR = 92,
            CS = 93,
            CT = 94,
            CU = 95,
            CV = 96,
            CW = 97,
            CX = 98,
            CY = 99,
            CZ = 100


        }
    }
}
